[versions]
kotlin = "1.9.21"

kord-extensions = "1.7.1-SNAPSHOT"
slf4j = "2.0.9"

[libraries]
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

slf4j = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
